FROM node:18-alpine

#CREATE DIRECTORY

WORKDIR /app

#Install dependencies
COPY package*.json ./

# run npm install

RUN npm install

#Bundle app source
COPY . .

EXPOSE 5000

CMD ["npm","run","dev"]